// Emotional ASCII art — generated from public-domain photography and
// woodblock prints. The night city, the ascent, the Great Wave.

export function AsciiArt({ art, className = "", size = "clamp(5px, 0.95vw, 10px)" }: { art: string; className?: string; size?: string }) {
  return <pre className={`ascii m-0 ${className}`} style={{ fontSize: size }} aria-hidden="true">{art}</pre>;
}

export const ART_CITY = [
  '       ...\'\'\'``^^`^^:^^``^``\'...\'\'\'\'\'`^^``^^^``^::::,:,,,^`\'...\'^^\'\'\'\'\'.                ........... ..........          ',
  '       ...\'\'```^^^`^^^^^^^^^^``...```^```\'\'`\'\'``^:,,::,,:^^`\'\'\'\'`\'\'\'\'.. .              ...........\'............         ',
  '       ...\'``\'`^^^^^::::::::::::^^^^:,,::^``^::^^`^:^^:::,:^^:^\'\'\'.               ...........\'\'..........\'\'\'\'\'\'\'\'\'.     ',
  '     ....\'\'```^^^^^:,,,;;;,,,;;;,,;;II;;I;;;;;;,:,:,,,::::::^`\'````\'\'\'............\'\'\'\'\'\'\'\'\'``````^^^^^^:::,,,,::^`\'.    ',
  '    ..\'\'\'\'\'``^^^^^^:::,,,,,;;;II;;IIl!!!!lIIlllll!lII;;;;,,,:^^::::^^```\'\'\'\'```````^^^^:,;;;;IIIIIII;;II;;III;,:^`\'.    ',
  '   ...\'\'\'``^^^^::,:::,,,;;;;;;;;IIIIll!!!llIl!!ll!lII;;;I;,,,^^^^``\'\'\'\'``^^^^::,;;;IIIll!!lllllIIIII;;;;;;IIII;;,^`\'.   ',
  '    ...\'\'``^^::,,,,:,,,;;IIl!lIlllll!!i>>>i!!!!lIIlI;,,;;;,::^^^`\'\'`:,,,,:,;l>IllIIlllllIIIIIIlIIII;;;;;;Il!lllI;:^\'..  ',
  '\'\'.....\'\'`^^^^::,,:;;<i;;Il!+zOO\\[<!!!i><>i!l!llI;;;,,;;,::^^^;^:,,!;,,::,,;l<IlIIIIllIIIII,:::^^^``^Illl!>>>>>!I,^`\'.. ',
  '`:^^...\'\'`^^^:^l>^\';,+-~>Il;~/xr+[)~!!iii!ll!lllI;II;I,:,;,,I^,,I;,;,,,;;IlI!~l!!!llllllllI^`,\'     .l!!i>~+_?+~!I,:`\'. ',
  '   ....\'\'```^::I!I;~<-}}_Il!i;;iiI-?>!i<<<><~~>i!lIII;,,,,:^,.,:l,,:,;;Ili><1t[~>!!l!!>>>>,^I!;;:`l,,i><<~-}}|}-<l;:^\'. ',
  '.^\'\'`````^<_>!II:I>,!}}1-;l!!<>~+I[)1~++?)0Jj?~>!I;,,;:,,:::,,>!i>i;IIIll!i[Jc)-i!l!>_[}[[,,,I;::^,,,>~~_]/|)kx}_!I,^`\'.',
  ' \':\',IIlll_}~l,;I<i<!{[__l><!;,l~i{1{!!i~{0mU_<!lI,::;^:IlII;.l+<~~:!!!l!!!-[_][!i_>~fYwd\\;;lI^.\'^;^^~?|nzr{{fqY]<l,:^\'\'',
  '\'.`\':I;,,,,;I^:;:iill>>+_?}~!,,:!~|[\\[?_+>!<{<>!!I;^;::,l~>!I`!!<[-!>>>i!!i_-1)-!<{-[rvUm\\;,!I^^,,;`;\\frv0(111wa1<l;,:^`',
  '`\'^`^;l,,;lII^,l+I;lI<~?]]]~<~II>?t)zzt([>><)}?_>lI^,:,;I-_i<>_{]~?i~~~?r?~}|/\\+I<_)vUUtrtIIIl:I<!l!>xuzzZ(!~xt|~>l;,,:^',
  '^,,;i><>!>!i;,I;!:I~!_i+???>~!,>i~t\\zcft\\_><|cu/~>I,;;^,l?_~_!~[}>II+{-)x}_1X\\[_|tft\\1vjc(I,I!l<~-_i>fvYUOf-][<l;;II;,^^',
  '\'^IIlll!l-II,,I,>><+~{[-?_|+~!!~-?vxCUuv/-i>|zzj_+i,,I^,i_}?_ll!l!!>>_>>]__1z(]/uxc|nrzn}+I;!;I,!__I>)({1}?~:^`\'. \'.^^^:',
  'III!!I>>>~II>!!>~li<~?]})?t-_i-[?[0JUnf0j}_-/CCv1]>I!<;l~?{?>;iI;I!ii<<<~][/c[>][)nfnxj?i>;:;,II>!~{){)\\/xc{,:^`\'.      ',
  '>I!!l>i>~!!<-<;<>!~]~-(\\1[x__+]]}(Xnf[+_<---tCJcxt~I,l!l~]{|1!ill!i<>!><_~!I~]-?[{/{j/]<!!,,!I,I+-uxY0wOJQ(-;,:`..   ..\'',
  '`.`:,<-}f|>!>!i+~+?~>)|}?}fi<!ii[?Om|{[li??-|YcYY|;,::I!+])tf~<<~~>++<<~+I`.!-+~-1}?}|)?_~!;I>;i](__uQpZQJ}-I;,^\'.   ^`\'',
  ':::;;;i><<!;i<~~_~<_]-{|{]t__>!>_}pU)[[<<+]?[uv);;:^ll;?-|JZU?-??[__?_~__<II;;\'^I+i<>~--]]+;I,l>~-)xzXLOcxC(!I,:^\'.  ,^\'',
  'l<>><-<<>>i~>-??)(|1{}|ft?!`:I!l;>)]<~{_~~(j{-?i`I,^I>!/{xM$d)]?_~,,;;l__\'    ^::::I;::\':;::ll!+]_-(\\fcQUvz|i!;:^\'.. ,`,',
  '~~_~+~?]??i>_(r\\)}|xv\\-]}~!!!i_!I;II:l!iI\'?)-\'\'I;I:^;!>n|U#$d};:^::^^^`^`    .::!i<>i!,.\'^\'^>trQUt}/czQkwOv/~iI:`\'.. ,:>',
  '^:^.\'`^lli!:,;~i;,,:I;^!l-?;;l;,;:^^.`\':;!l^`.\':\'. .^:!tva*#Y~^`^`\'....   \',;```i>!>ll,.\'::;Inqampn/XCk$@%av?<l;:`\'\'\'?[+',
  '\'\'  \'`\'  ^;!>I!;ll:``,i+-{{>?|)],....:,>jYvi\'..   \',;;_fYYmJ(lI;:`.  .,..\'\',i`\',>!I;;;,\'\',,;I{uvzUvJx\\XJmbkL(-<!;:::IUwL',
  '       .\'::l>IlII,:,,;!>}\\/\\(?+i::^I!I;,!{};\'   \',,;ll~<?nQ(~,^^^\'.\'. .....  `;i<>lI;;;:^;li_tw$$*Qv(1t/t)(t1?~!lIIII{rz',
  '        ...Ii!><ii~-?-{|zj[<<<>!!!>I;;+^^,l,:^^lIII><~[_)UMMu:` .   \'.  ;:.  .Ii>i;I;!~,:;!>]U$$$$0nj)|r/\\t|\\|}{{1}[]~~<',
  '\'  .   .:<xOdhZJX(}?->!iliI^I>!lI,,.,,~:\'\'\'^;l!+I!~~~>?}vUYm/::`..           .,I!!,;;I>,;l!_}cw$$8Om0cwhqwmxt)<|vrrnzn/{',
  'l:\' .\':l~r*$$$kz\\<!l::^l:;;:I!;,:^^\';;+:    .^I~~~?<~I~tmC?u(i,,`\'.           :III,;,,};!!!+-1Q$$o0wZUdhpOC/?~;<[[)/QQJv',
  '[>Il!<-[)x/r\\?i!,;,,I::::`\'\'\'.....\',;;i`      `+-~]~il]nan_/0f>!,`\'\'...       ^,,^.. \':.^^\':I<u$$oqkkUzj[~-{)~;::;i;l_[\\',
  ')|?-+-?~lI,Il,,;:;!!,:;^       ..  \'\'\'..    .;i--~?}~]/JmvXW$Z{]~>ii!lI;;;,^ .`,,i^. ..`^``^,l_\\xuu\\j|/\\[[~!<<;,^`::^`^^',
  '<i;;I><~<>+?i;I<_!!;<I,^\' .\'  ..:^ ....\'\'```i+I__>,;<1YJn\\/cr|//){}}}[[]--+! ^:\'.^^^\'\'\'\'\'...\'`^:^^^`\'``^`^^\'...... ..   ',
  'I>_-?]-~<i><!!~-i;^^^```.   .\'\'.`\'       \',:~<;<l:,I>(Jj\\}\\||{}tvuuvcvrrx(1]\'l;`\'\'`:,;,^`\'..  . \'\'... .\'\'...     .. ..  ',
  '>_~i>!;;:Ii;\'`,,\',^^:IlllI;Illl;;;,::^\'.:;i;~I^i;,;>~{YpJurx?I:!}{{{)}l>(-,<^:;!;:^\'^,,:^^^^```\'.....  \'^\'\'\'.......     ',
  '!>;^;<~~!^,^\'\'\'`^,I><<<><>i>i!!!lII;:^^,i<<:~I`l<!+/(r0Qt/{\\<;lIII`  :I^`,^:,^I~<I,:\' .\'^:^:^^^`^`\'..   .\'\'....         ',
  ',I,^,~<i,:,I;II;;Ill;l!l!llI;,,II;;,^:<~!,!:+<^+~>>_]|YX(|f1--~~~~<<+~~<!i-(/[>i>!lI,\'  .`^:::^:,,:^^``\'\'...            ',
  '`::^i?j>^:::,I:Il!^`.`^^^^``...\'\'\'.\'`;~+:,>;-<:~<i!!<jOcrf(<-\\|\\///jrjtt\\/vO0v+l~~!llI:\' .`^:::,,,:^^^^:^:`\'\'...        ',
  '\'^,-}]1l\'\'\'.``.,!>\'.     ...\'^\'  ..\' :><,:><+_<<!!l_)Y0/{)f)\\nuXXUUQOmZmQ0bM#U?i~+<>!!l:`.  .\'`^^:::^:^:^^^\'..\'.        ',
  '^^,>>>,,,,,:^^.\'^,^^^``\'`^:^^:^.... .;_-,;-~_-!;,;I-vqv!;;1)vdk%$$$$$$$$$$$$$ht<-+<~~illI^.  ..\'`^^:^^^^^\'....\'`\'.      ',
  ',::ill!~~<>>l:^ .i>>~~~~<<>!II,^``^:l~__;;<l+>i!_+?}Ubj~~>>+c$$$$$$$$$$$$$$$$@U<<i<~_<llI:`.    ..\'\'\'\'^^^^\'...\'``\'..    '
].join('\n')

export const ART_MOUNTAIN = [
  'Q00000QQ0000OOZmmmwmwwqppddbbbddpwmZZZZZZOOOOOOZZZZZZZZZO000O000OZZZZZZZZmmwwwwwwwmmmmmwwwwwwwmmmmwwwwqqppppqmddddddppqw',
  'OOOZZZOOOZZZZZZZZZZZmmmwwwqpppdddppqqwwwmmmmmmmmmZZZZZZZZZZZZZZZZZZZZmmZmmmwwwwwqqqwwwwwwwwwwwwmmmmmwwwwwwwqQCpppppppddd',
  'qwwmmmmmmmmmmmmmmmmmmmmmmmmZZmmmZZmmmmmmmmmwmZmZZZZOOO000OOOOOZZZZZZZZZmmmZZmwwwqppppppppqppppppqqwmwwwwwwwwznwqqqqqqppd',
  'ppqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmZZZZZZZZZZZZZZZZZmmwwwqpppppqqqpppddppqqpppppddddbkbddpppppqqqO[\\qdxXpqqpqp',
  'dbddppppppppppppppppppppppppqqqppqqqqqqqqqqwwwwwwwwwwwwmmmmmmwwwwqqppdddbbbbbbbkkkkkbbbbbddddddbbbbbbbbbbbpn~\\LZ{xkbdddd',
  'MMM##***oooahhhaahhhhkkkbbbddddddpppppppqqqqwqwwwwwwwwwwwwqwqqqqqqqqqqpppddddddbbbbbbbbbbbbbkkkhhhhhaaaaaaqr?[(jfrQhhhhh',
  '&88888&&&&&&WWWWWWWWWWWWWWWWMM##***oaahkkbbbdddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbkkhhhhhhawf?]uj|tXhW*#M',
  'ooo***###MMMMMMMMMMMMWWWWW&WW&&&WMMM#############MMWWWWWW&&&&WMMMMMWWWW&WWWWWWWM###MM#######*##**********Zr|)(//1jzwofUW',
  'ooo****###M#MWWWWWWWWodpUCd%$aZZM8$$Moo#MMMM###MMWWWWWWWWWWWWW&&W&%&&&MMW&&88&888%%%%8&&888kd&&WW&WWW&WMMC/f[/t/})/zrtvW',
  '##MoWW&88WkwZbhWWodwwOUxtuULdOntzwZm%$BkhaM%$$@BWM*M$$$$$$#W8%MMWa*bdkqqdka#okdbpa#MoW%WdwC|/mh88MW&MCM88hn](t\\t+}XJzt1o',
  'b8pnadmQYuruucXczXLCJLXfjjntjcXYXuxnvQ&$dLLQmo#dOZq8$$$BhkmmZOQOZm*#&#M#bkbkkdhdpbqqL0pUtrt][nYLbZCZ0)m*dx/))/(u)\\1{{]!f',
  'fCc+nCXnxxxxxrnzUYJznn)uxxvuzLZYx/zCYz/tcQXuxv0qZLZ$$$$$$$@*$$$$$$&W%@$$$$$$MwqbhbpqZzntjn|?>{XZ0tvJ/]udX?{f|/]))]]_>~,]',
  'I{Y+cJxUYzcccccXzucvv{IfvzXcjjv))tvj(tn|)(\\rnnmpdp0dW$$%$$$$$%$&#W%$$$$$$$8MWWbdommmOffrun)+<[ndax][{{1wv[!(|++)|{)++I^{',
  '-](<jvtLXYYUUUYYz]xUCt,<Ucrjffxrt()|)|zv||11tn0ZqakLunxrYCZJULZmWdqbo$$$M#odbbpZQJX/tfxvvnt?_)1|f)???_)xtx)_}|tnf)[[{>;{',
  'I!{~tt}xJJYUCOcjC-)wm/l>/_[xjxrrjt|||(|u|r))1)|xfxLw0JcxrrxxX0LOpwwqpaoakhppZJXJ/)(\\tjxuf/t)(t}!>;__+[}fj})(()[{}\\nr|f_+',
  'I][<]1>>[CLCCX)+X(](f?!I;~!tnvnrnft/\\|(r/\\|))){)({)jJLXunxxnnnn0kqqZmZZQJJJUvrfJLCvtjxuj))\\-}{)[-~!II~t\\]]rtntff(~){+!I<',
  '?]<!))-!:nJLZ/!<u)?>|{;,,iItvYUvvrftttrvxtj\\()()))))/njxxnvzzXUqkZJCCCCUYzzCL\\ndwbOnxcXf)]]l>)/j)~++[||{-(ncUvx|?_!I!~}|',
  ',:~!-{{>!{)jJf<])~__~_I``!!]nvXczcxjrcXzunrf/||\\||/\\(\\rJ0ZwpqmZmZLLCUYzcvnnvXccXcvncYrvx-_!!-|(t/(]+)|t/cu1/c\\]-<><~I,~>',
  ';I,:,l~!;[_[x\\}{?<l<-~;\'\'!l_rcYzzzvrxcvvuuxrjfjvurttt-)tjxnxjfuXznjrxzUzvuuvvnuucc/xc{/u/]>_!(\\f/?>i]ftt|)ftn{[{!I_+}??]',
  '^^ .\',I,l<+~tj}+<,`I]~::`:;l{zzzcvvunvczcunxxxnvzcnj(i?t\\///tt/////t)1rccczcvuxnvn}|t-{<[[?)~{)}[>><-xr\\(vz/(/))<I~--}{]',
  '`,.\'.:<iIl^`\\(_1_\'.<<`\':`^:`Ijzzccvvvuucccurnnnnnnnr?ii|[\\jrnuxrrrff_>nccvvf/vt})n))1?[}[1-~<}1[?!;_\\\\(fUYx()xt{}+?(/fr\\',
  '...   ^l:^^,?-\\),  .:!!,<:^` !vczzzzccvxvvv{rnxunnux{<-\\[(vzYCOYzXf]<<{vvvx)}fx(}|]-[+]\\|~II?t?-]l<(xf}{cv)[(j}?_>?1)]_+',
  ' ;l,\'   ^;l1_I<I. ``\'`\'\',:..\'.|jfXzzzzr1cxr[}{[vnn)f-]?([}/rjfrrrf]~~_~(vnf}-1}}?--}<!]/)?~[({)(\\-+fx\\1\\Xv/\\(]|(?<<l}(}-',
  '`!,...  \'^~)>:^   \': .^\'`\' .^ +f(zj/|uj)n}]->]_//}+[--}1-<(xxnnnr[-~?<)rvf\\+~[[-}[?{-{){/}{)j){<!i-)n)[tx|/)[|x\\({}[-?][',
  '.   ..   `:?~I\'.    \'   ^, .\' `l<jt[i[)|\\[Il?-!!_+__+())],l[tnnu{-]-?>+}|-><[]1-[))])}]/(1|(((\\]i,~]fr\\+/1t)/{[{]]}{t|1{',
  '`       ^,I!I:   . \':.         :))/[+<[|]-^,_<!I~?<-{t(}-;:i\\nnu)_<>>i]?<I,l-f1|{)[_|\\)()(?_})[??//\\xv/?!+(1][{_+>+>[}_]',
  ' .      ,I,\':`  .\' ..       .  ^[||1_i[)_i`^^?~,;,I>!-_~<^\';1/rn(~,.::::`^:\'l}-)|111||]1t}+{(/)_\\f(tx/})>?{--]{/r_~]}1[}',
  '    .    I!`   .^.         .   _)~[]_-{1<I^:l[i\'. .:\'`,;l\'`!|xrf+l.      `.  .!(])]+)]-t/(_}1}(_<)j)\\tt1}_il!1t\\z[{|(/){',
  '     ...    \'` .\'     `.   `\'..<}_}~~~>>I\':I,l.^I,ll!i><+~-](jXJzvnfft|(}{__[~<|}/))/t||t1_<>+/jxtjf)1/j}[l+-/jtQ[?-1_r}',
  '...       ..^:``.     . . .::::`:^,,`. .^^^:,,:;!!l,l>>+-]+_])tttuzzJQCLLLZ0YUYtnvnuvrf1j|1->}vx|tjr(([rru{]\\rt)Y/}[unU|',
  '\' \'^^..l: :l!Ii:\'^\'\'...  \';;^\' ^!!,;^:^\'\'\'\'\'\'`^:,..:!^?I,!~?]~>-+_>-}ruunt|(/1?}(\\j/t\\t}trf(1|xxtr\\t/{]fzU\\?[+->n][(f\\r-',
  ';>+){!!<>l!!<!~>~\\+i+??!l;;,l~>-(n]?_;>_iii++]]]_[_1t{nt{1/nfxr/|t|}-}tt)(}||t{|t(]{-tr}j1}//|f|[/f{t{~}JCj]~l--z[{[\\}|_',
  'vXvc0QCJLCQ0mL0LLOUcxuuuYc/nvvuUCmLLJUJXnXzU00LQCJzYCJJcxnz\\vXvuCCJvJJUJYJYJzYzQZLQ0cnzunvfcjtXn{r0nX/(JLUrf|{?tX_({rfr}',
  'bpmmddpwppddhwZZCCYJQLbZZbQwLZdJXpOCObdQLOJQQLzULzzxnucvfucnczzXCvnf/n/tjnvYcfxczxucXvzCm0YQ0wwbpmmZLw0CwZmOZwQJJnXZOQJc',
  '0LZJZLCmZp000LO0OmwphkdZZpqXX0CUJzzcOhddwL0pLQcuJYCUmwpJwZw0nvnvYnnrrxnt)rfnnj(ff[t|[(nvQmCJUYCddJXYJ0JXCZZCzLUXJOJYXLYY',
  'ZCZZZZmOUOOqLZmObo0mdqOLQ00XJxznnjvJdmLUCUqQLCttczzLUCLzXZZQnuYzYvX00zpZLOm0Z0f)1fCx_]xcnCJCcnvQQCzXruJJCQufunYrCCOCXvYz',
  'YvO0Z0JCcCCv0LZQLQmOQLCczQZwmct)|XnJQYzvQ00JCmUvncCuXxzCXLmCJrXOQmLwko*&8MMMok0/rLOxjXzQbwOmL0OCzcXnjOvzYLYcxUCJU0O0OYZ0',
  'mLYmQJvcuYJUXQZC0ZZOLZw0cLQQwvXxY0Q0CQLUznnczzYUJLcxCzXLmCdXXOpohabdp&&%%&W%o*dYCOYncUXQqZp0LOQXnxrC0QJzYLJZQp0QQ0wYXYZ0',
  '0CQmOZJvczvUpZ0qYCCuXYCdUJXruUC0QmZbwqJuUzt|zUnJZYnCYutLUUvvJmCdo#ah*WW%B%WW*pkwZYULUCpbpwp0QdOzcJUpczcnvUjOcX0wL0ZJULYY',
  'xXcJXcvnfnnvQqLXcYnxYnfvjxznrXXJQQJUY0JYqZYOJLzCnc/frxvO0ZvYQZQZbqh&&M&&%MW##QdaqQZZ0Qpd0ZwYQZJYJUnCJXLzUcXUXcxJQznXvcrJ',
  '0ZJcYQJUYczXCZvt/f/XX1nvvJuczvXLJXYUQm0LZZ0CQpUxcXfnCzvQ0XrcZwUYJvk&&h*MZddZdZmOmOJQJOmdCuZcpmUUJJJLXJcJXYULCXcCqQXv0LLm',
  'YCLpqppJvxYOXJxJUjtYc[zXzXfUXjvOUzYUQdZmpdznUccXLYZmmmYxCzzQZpwzCfrhWddoUqdUXJ0Uq0YnXYmbwYQXpdCLv0ZmqccYfLLXQ|nLw0XvQUXZ'
].join('\n')

export const ART_WAVE = [
  'Zmqpddbkbdbkhoohaahhaahhhhaaao**#oo*#M#MM#*M#*##*oo*#MMMMM###MWWMWWMMMMMWWWMWWWWMMWMWWWMMMMWWWWWWWWM###MWMM#M##MMMMM##oh',
  'mqpdbbbkhhao**oaooaaaahaooo**#MMMMM##MWMMMWWWWWWWWWWWWWWWMMMMW&W&&WWWWWWW&W&&&&&MMW&&WWWWWW8&&&&&8&WWWWWWWMMMMMMMWWWM#*o',
  'wqddbbqwqdb*###o**ooooaoo***#MMMMMMMW&WWWMWWWWMMW&WWWWWWMMMMWW&WWWWWWW&&&WW&&8&WWW&88&&WMWWW&&8&W&&&WWWW&WM###MMMWMWW#oa',
  'wpbbbdZmxamoo**oo*oaaahhaoo*#MMWW##ooooahbh*M#oo#MWWMWWMMMMMMWWWWWWWWWWWWWWWWW&&&W%BB@B%WMMMW&&WWW&&WWWWWWMM##MMWWMWWMoa',
  'mqdbbbmqfhpoo**oooaaaoooo*#MMMMohkbhM&88W8BBW#bhdma#*#M&WWWWWW&&W&&W&8%%%8WWW8%%%B$@@@@B%W&&&W&WWW&888&WW&WWW##W&WMWWMoa',
  'mwdbbdmaU*qao#M#oooooMMMW&&&Moh#&%@$@$$$$$$8Zmmk**oohMoo#MWWWWW&WWW%BB@$$@B%B@@@@@@@BBBBB%8888&&WWMWW&&WMWMMWMMMMMMWWMoa',
  'qdqpwp0bv*wh*#######WW&WMoo*#&BB%B@@@$%#abbbwkOm#W&mwOMM*dpa&WWWWWW&%BBBBBBBBB@@BBBBBBBBBB%BBBB%8&MMWMMM#M###MM######*ok',
  'qpZX0dZoCdmba*MMMMMM&WoqdW%%BBB&aq#o@BWQO0QQzmbwQpqLmkZpZOwdWWM###MM8%8%BB%%%BBBBB%%%%%B%%%%%%B8&WM##*#*o***###***o*oahb',
  'wpZu0qOMhvmpkaooo##*hdh#%%%%&##mmmc?(JY0Z|>) lJb0aMbLbmwwmwZq**##W&&%88%8888%%%%8%%888%%%8MMWW&WM#**o*#*aaoo*#####ooahkb',
  'ZwO)QqQJL0Omdbbbkpqpa&%%%%%$MmZ0CdJ>,^ ()[~   >cmhqpdmdoMpbkkhbh#MW88W&8888&8%%8888888&&&WMMMMMM#*oao**oaaooo###o*ooaakk',
  'mw0xLwOzL0QmqdbwLhW8%888%B#YvJ{\\?;+_ \'`.  !\'. ^ |qaYwmMbabkW%%oZOmwqW&&&888888%888%88WMW&WM######*oaaoaaoaaaa*#*oaaaaakk',
  'ZmmfQwQ00Z0mwwmw#&&&88888%%i + ^I  ;l\'  ,;. \':;^,`{|)QopdZZbdhphkdahkM8&888888%88&88&&8&8&&##MMM##*ooooooaaaao*oaaaaahhk',
  'mwqUZwwwmZwmL0M%8&&&8&8%%%BX`. .`  _;^ >!  `,.    \')d%bQkpOdmbkZoW*#OqhW&88888%%88%88888%%8WMMWWM****#**oo###*#oaoo*oahh',
  '0mwqwwwmOJLObM%88888888%%%%$dn1(u+i<i `i.\'l!,^\'^I<+/mkbZmwqdZ*8wbhOZ#Wd*&WW&&8%%%8888&W88888&&888WMMWWW&WWW&WMWWMMWWM##o',
  'ruuxxf//xOaWWM8888Mawb%%%BBWM@$$hZJ], <Ii:<I;``]>rpho8hZqbwbppM@q0Qw*WWWWWWW&8%%8%%8&&&88&88888888W&88&8&W&&WWWWWW&WWWW#',
  'lII<1x0dM8WW##a0pkwQLoB8M8BqLmphMm??l\\/?~iI^` Iiv8%88%&awhOh**mwWpqmO0MMWW&&&88888%888%888&888%88%88%%888W&88&WWWWWW&&#o',
  'fuLb*#M#o#8&WZOZhkLLJpdoOh#OLamCkoowawu+-]!;`^~<h88&&8&W&8*W88*m*bmqWoWW&&&&&88%8888&W888888888888888888&WWW&&&WWWWM###W',
  '##aw0mqCXObmv(zb#MoOJOxdZppQCkppoUZkhwbqwOCj,ll-*&8&&88&&W&&W8M#hd*p#MMWWW&&&&8%8888WW&&&8&&8888888888888WWWW&88WW#oW%BW',
  'oaadZYUCUCZ0).;{}-zqbmvLQZo}`~n;|!?QYppkJ~;<; ;x&W&W&8&WWMWWWWWWMWWMMMMWWWW&&&88&&&WWWW&WW&&&88&&88&8&W8888&W&&&#aMB@@Wq',
  'awQUYYmJQL0pc])l^^[hbQZ0Zd8qf/1c?.,~ljYz)?.,I :|W&&&8&8WMW&W&&WWW&W&&WW&8888&&88&WWWWW&&8&&W&&W&88WW&&W&88&&&8Wa#B@@&Mqm',
  'dJvYQ0)~zQrJOt/[>;!XZLZYOkbha*pwz~~l`^-1]!`> <l?Z8WWWWWMMW&W&WMW&W&WWWWWW&&8&&&WWMWWWW&&88&&&&&W&WMMWWMW&&&8Woa&BB@@8*mJ',
  'w0Yn?cQ-,>!:{~ +l>/LCUvY{+(Ommq0u[`i`,I>!``I<I,I{hM#MMM##MM#MMMMMWWMWWMMMWWWWWWMMMMWWWWWWWWWWMMM##o*##*W*ZadJh@@B%opdCz}',
  'ZdX)}/p0/)<`:l ,-<-Jxl,-->\'<ULu~}-i i>,(ZJ[]|; :1[woaooooo*o*####MW#######M##M#**o***ooo**ooohkkdppppppQx0ZmW$@B8aqmL}<`',
  'Q0bpdwLpQUu1_lIiI>l+i!;>>[;\'>,<},liIi+O$$$$&bqQ}\'^<YmmmmwqpdbbkbhaakkkbkbkkhhhkbbbdpddpwwmZOQLJJUYYYvf?i\\ZW$$@@Bobha(>;:',
  'ZJO0OQJqab0JCz|[Il,:;<>I`,,~>\',;lj}|fa$@@$@$$$$@U+^>tYYJUUXUCJLCLQ0LLCCCLCCLLLLCJCUUYYXzccuxxxxxxj}(+([vo@$@@8Wdpvr/}I.\'',
  '00QJLCOh#dZnuOJzzu)[_>i:`,>>;I><;[O8$$@@$8B$@$@$$m/!`]rnUrjrjrjffrjrjjjffjtxxfjjjfjfft//tt/|\\\\/|?[-}|ca$$8&%@d1{ii;^,;,<',
  'Qmc+~u)xUi{xznvCQJJLZLzt()/}i,!}Y*$@@@$$Wkw#B$@@@8hwz{-+)((|(|())(()((|()f0WWqx|\\||(|((((||(|(\\rtxzOMBM*bad\\\\};. \'I_(vZh',
  'ba/ :i]i}:\'+fczxccL0LCf(uxrZh*MB$$$@B8WomZb%B$$@@$@phB&wwZ/[{1{}}}}){{)xpM$$$BBwj)}{111)][(fnYLwhW%$$@oJuvf-,I<)xzUqo&%W',
  '**o{^`>~:II  >(vXvxtvZ|_|Ub%@@@B@8#&BhqhbwC#%o%$8%$$Wqhom#*Zj1[}}}{fxuCpC-\\cWcYhhdu[]{rCcYQOwboW&&waZXm0cjftYpkc(/0M&M#*',
  '**o*Zxf]--~1(/vdaoabd##*8BB%%B@@%Z0MWd0ZZm##bpdMkZ*a8@dkwZM$%kU|?_~;^`;?(?>~-iI>+?-<i_cmwpaWWbOfr\\{ft/Umk#8&Qf|rw#Mo#Map',
  'oo*#MWMMWW&8%B%W&88888pZqbhW%odop0k0mwqd#baMbdkwd(|OdW$#Or)w#\\J#%pOOzr\\}?}{{rnnXUJQwmahpbJJLbhcnzQpaW&oCf)-?t0#WMaaaL/-i',
  'oo#apqpboW8888bqkMB%88aZCdbw#Mhmkbdm#&B$$Mdpp8Q~cv\\}0Zp0*L} )Z|]Yw}}Q#%%8&#MMM#MWWWWhaMaka*MW8%WmCz(||[I,irw#apwZt))?II^',
  'ooohdOXO00ZbdpmqhhzZ*ww0abbQpBB%B@%pbpkoMopwb$a_-|rzJct1u%oJ?<?\'\'+t{;ivk&%WWMW%@B88&#qpk*#Wo0OZYr({[??[vp#$%MC1++__-[|fr',
  'aaoo#ahkhwu0ZphopmI>Q00kkZpw#MMqo%Wqm0dmZp0opa$U,I[I/Jn{}fcOdwUf-\' l([;;(QkW8WJfXqa#Mpznf/|(}??-<!I,<)0#8WMWMaqYx\\]<><il',
  'bhooOr|nLJt}{}[Ql>IlcmCZwmkZmOamL#dk0wmmbLwwwp8$n\'^I.^(Yntnf/rvUxf(_ll>; .,]jCqL\\~!~\\n/\\}?~)[)[(_~)LW8#omYvc|<II_{([[|/|',
  'bap{II,lt>iiII`I]}\\QpZZXLQQbdOohmdZJp#|~v+tULwo#Wwi.,. ;?fczzcvxjfucJUzf([~l,,l_|ft1^^-i??:[,i]Cm#B8okqmYnxt|/rvzx[<!I;;',
  'bmI\'_:?z_i,``i>!/aC~_+zI;l/QZaC0kOaM#8Q+i,[~~b0Xd&*xi` .\'^<\\ucXYJYznnzmZOOQQLLUcxxufn{j[1/|Q0bW88Wk\\!I,,,::^:`\'\'^`      ',
  'hr ,l\'!~`-~ `_;\',i_I\'..:,`^\'}M*o#b/w8%@YUL|?:(|,}aM88d/l    ;+)vObahkbdpppmqmZm0Q00LLLUpZZqZYn/}+<<<!I\';+)(/xz0qdqO0LXx\\',
  'o/\'^`~I;`:? ^l   !.i\' ;>.;  fo#dUui\'cC|)<QO1!;~  ~cUpa&aQf?i^ .\':i_}1[__|ff\\(|xcJwoMW&%@w{_>::;Ili~])rYqao*##MM*oahaho**',
  'L:!i,::I\' ;; >   I..,:.i.^\'I]C(j~+JzmO|LLQwUQZL?\' \':txx0oo&dpwZzrf|)))\\ffuUQqko*aahhhhhho*ahbbbhaao*o*okkdpddkbqpppppppq'
].join('\n')

