INSERT OR IGNORE INTO schools (id, name, province, city, lat, lng) VALUES
  ('st-matthew-s-high-school', 'St. Matthew''s High School', 'Eastern Cape', 'Keiskammahoek', -32.691, 27.143),
  ('clarendon-high-school-for-girls', 'Clarendon High School for Girls', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('hudson-park-high-school', 'Hudson Park High School', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('port-rex-technical-high-school', 'Port Rex Technical High School', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('selborne-college', 'Selborne College', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('stirling-high-school', 'Stirling High School', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('west-bank-high-school', 'West Bank High School', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('khulani-commercial-high-school', 'Khulani Commercial High School', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('dale-college', 'Dale College', 'Eastern Cape', 'East London', -33.015, 27.912),
  ('get-ahead-college', 'Get Ahead College', 'Eastern Cape', 'Komani', -31.898, 26.875),
  ('ntsonkotha-senior-secondary-school', 'Ntsonkotha Senior Secondary School', 'Eastern Cape', 'Lady Frere', -31.703, 27.236),
  ('queen-s-college', 'Queen''s College', 'Eastern Cape', 'Komani', -31.898, 26.875),
  ('collegiate-girls-high-school', 'Collegiate Girls High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('grey-high-school', 'Grey High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('lawson-brown-high-school', 'Lawson Brown High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('victoria-park-high-school', 'Victoria Park High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('westering-high-school', 'Westering High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('westville-senior-secondary-high-school', 'Westville Senior Secondary High School', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('ho-rskool-brandwag', 'Hoërskool Brandwag', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('muir-college', 'Muir College', 'Eastern Cape', 'Gqeberha', -33.918, 25.57),
  ('molly-blackburn-high-school', 'Molly Blackburn High School', 'Eastern Cape', 'KwaNobuhle', -33.735, 25.352),
  ('nomaka-mbeki-technical-senior-secondary-school', 'Nomaka Mbeki Technical Senior Secondary School', 'Eastern Cape', 'Dutywa', -32.104, 28.296),
  ('diocesan-school-for-girls', 'Diocesan School for Girls', 'Eastern Cape', 'Makhanda', -33.31, 26.525),
  ('gill-college', 'Gill College', 'Eastern Cape', 'Somerset East', -32.718, 25.588),
  ('graeme-college', 'Graeme College', 'Eastern Cape', 'Makhanda', -33.31, 26.525),
  ('kingswood-college', 'Kingswood College', 'Eastern Cape', 'Makhanda', -33.31, 26.525),
  ('woodridge-college', 'Woodridge College', 'Eastern Cape', 'Thornhill', -33.886, 25.243),
  ('port-alfred-high-school', 'Port Alfred High School', 'Eastern Cape', 'Port Alfred', -33.6, 26.89),
  ('st-andrew-s-college', 'St. Andrew''s College', 'Eastern Cape', 'Makhanda', -33.31, 26.525),
  ('victoria-girls-high-school', 'Victoria Girls'' High School', 'Eastern Cape', 'Makhanda', -33.31, 26.525),
  ('bethlehem-voortrekker-high-school', 'Bethlehem Voortrekker High School', 'Free State', 'Bethlehem', -28.231, 28.307),
  ('bloemfontein-high-school', 'Bloemfontein High School', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('grey-college', 'Grey College', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('ho-rskool-fichardtpark', 'Hoërskool Fichardtpark', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('ho-rskool-jim-fouch', 'Hoërskool Jim Fouché', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('ho-rskool-sentraal', 'Hoërskool Sentraal', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('phehello-high-school', 'Phehello High School', 'Free State', 'Kutlwanong', -27.953, 26.782),
  ('sasolburg-high-school', 'Sasolburg High School', 'Free State', 'Sasolburg', -26.812, 27.817),
  ('st-andrew-s-school', 'St. Andrew''s School', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('st-michael-s-school', 'St. Michael''s School', 'Free State', 'Bloemfontein', -29.085, 26.16),
  ('welkom-gimnasium', 'Welkom-Gimnasium', 'Free State', 'Welkom', -27.977, 26.736),
  ('african-leadership-academy', 'African Leadership Academy', 'Gauteng', 'Honeydew', -26.058, 27.921),
  ('allen-glen-high-school', 'Allen Glen High School', 'Gauteng', 'Allens Nek', -26.17, 27.927),
  ('athlone-boys-high-school', 'Athlone Boys'' High School', 'Gauteng', 'Cape Town', -33.925, 18.424),
  ('barnato-park-high-school', 'Barnato Park High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('bryanston-high-school', 'Bryanston High School', 'Gauteng', 'Bryanston', -26.061, 28.024),
  ('crawford-college', 'Crawford College', 'Gauteng', 'Lone Hill', -26.017, 28.016),
  ('fourways-high-school', 'Fourways High School', 'Gauteng', 'Fourways', -26.015, 28.01),
  ('greenside-high-school', 'Greenside High School', 'Gauteng', 'Greenside', -26.157, 28.023),
  ('helpmekaar-kollege', 'Helpmekaar Kollege', 'Gauteng', 'Braamfontein', -26.191, 28.035),
  ('ho-rskool-florida', 'Hoërskool Florida', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('jeppe-high-school-for-boys', 'Jeppe High School for Boys', 'Gauteng', 'Kensington', -26.198, 28.105),
  ('jeppe-high-school-for-girls', 'Jeppe High School for Girls', 'Gauteng', 'Kensington', -26.198, 28.105),
  ('king-david-schools', 'King David Schools', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('king-edward-vii-school', 'King Edward VII School', 'Gauteng', 'Houghton', -26.155, 28.053),
  ('kingsmead-college', 'Kingsmead College', 'Gauteng', 'Rosebank', -33.955, 18.474),
  ('michael-mount-waldorf-school', 'Michael Mount Waldorf School', 'Gauteng', 'Bryanston', -26.061, 28.024),
  ('parktown-boys-high-school', 'Parktown Boys'' High School', 'Gauteng', 'Parktown', -26.177, 28.038),
  ('redhill-school', 'Redhill School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('roedean-school', 'Roedean School', 'Gauteng', 'Houghton', -26.155, 28.053),
  ('sacred-heart-college', 'Sacred Heart College', 'Gauteng', 'Observatory', -26.18, 28.08),
  ('saheti-school', 'SAHETI School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('sandown-high-school', 'Sandown High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('sandringham-high-school', 'Sandringham High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('sir-john-adamson-secondary-school', 'Sir John Adamson Secondary School', 'Gauteng', 'Robertsham', -26.26, 28.013),
  ('st-mary-s-school', 'St Mary''s School', 'Gauteng', 'Waverley', -26.141, 28.064),
  ('st-david-s-marist', 'St David''s Marist', 'Gauteng', 'Inanda', -29.683, 30.94),
  ('st-john-s-college', 'St. John''s College', 'Gauteng', 'Houghton Estate', -26.155, 28.053),
  ('st-martin-s-school', 'St. Martin''s School', 'Gauteng', 'Rosettenville', -26.254, 28.052),
  ('st-stithians-college', 'St Stithians College', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('st-peter-s-college', 'St Peter''s College', 'Gauteng', 'Sunninghill', -26.037, 28.076),
  ('torah-academy-school', 'Torah Academy School', 'Gauteng', 'Orchards', -26.13, 28.07),
  ('waverley-girls-high-school', 'Waverley Girls'' High School', 'Gauteng', 'Waverley', -26.141, 28.064),
  ('westridge-high-school', 'Westridge High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('yeshiva-college-of-south-africa', 'Yeshiva College of South Africa', 'Gauteng', 'Glenhazel', -26.128, 28.078),
  ('alberton-high-school', 'Alberton High School', 'Gauteng', 'Randhart', -26.274, 28.134),
  ('ho-rskool-alberton', 'Hoërskool Alberton', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('ho-rskool-dinamika', 'Hoërskool Dinamika', 'Gauteng', 'Brackenhurst', -26.32, 28.085),
  ('ho-rskool-marais-viljoen', 'Hoërskool Marais Viljoen', 'Gauteng', 'Alberante', -26.268, 28.127),
  ('st-dunstan-s-college', 'St Dunstan''s College', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('boksburg-high-school', 'Boksburg High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('ho-rskool-voortrekker', 'Hoërskool Voortrekker', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('st-dominic-s-catholic-school-for-girls', 'St Dominic''s Catholic School for Girls', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('germiston-high-school', 'Germiston High School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('st-benedict-s-college', 'St Benedict''s College', 'Gauteng', 'Bedfordview', -26.177, 28.139),
  ('st-catherine-s-school', 'St Catherine''s School', 'Gauteng', 'Johannesburg', -26.204, 28.047),
  ('cornwall-hill-college', 'Cornwall Hill College', 'Gauteng', 'Irene', -25.866, 28.211),
  ('ho-rskool-eldoraigne', 'Hoërskool Eldoraigne', 'Gauteng', 'Eldoraigne', -25.846, 28.176),
  ('lyttelton-manor-high-school', 'Lyttelton Manor High School', 'Gauteng', 'Lyttelton Manor', -25.842, 28.166),
  ('southdowns-college', 'Southdowns College', 'Gauteng', 'Irene', -25.866, 28.211),
  ('sutherland-high-school', 'Sutherland High School', 'Gauteng', 'Eldoraigne', -25.846, 28.176),
  ('tshwane-muslim-school', 'Tshwane Muslim School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('mamelodi-high-school', 'Mamelodi High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('afrikaanse-ho-r-meisieskool', 'Afrikaanse Hoër Meisieskool', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('afrikaanse-ho-r-seunskool', 'Afrikaanse Hoër Seunskool', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('christian-brothers-college', 'Christian Brothers'' College', 'Gauteng', 'Mount Edmund', -25.758, 28.336),
  ('clapham-high-school', 'Clapham High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('cornerstone-college', 'Cornerstone College', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('crawford-college-2', 'Crawford College', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('hillview-high-school', 'Hillview High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-menlopark', 'Hoërskool Menlopark', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-oos-moot', 'Hoërskool Oos-Moot', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-overkruin', 'Hoërskool Overkruin', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-waterkloof', 'Hoërskool Waterkloof', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-wonderboom', 'Hoërskool Wonderboom', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('pretoria-boys-high-school', 'Pretoria Boys High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('pretoria-high-school-for-girls', 'Pretoria High School for Girls', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('pretoria-secondary-school', 'Pretoria Secondary School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('pro-arte-alphen-park', 'Pro Arte Alphen Park', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('st-alban-s-college', 'St. Alban''s College', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('st-mary-s-diocesan-school-for-girls', 'St. Mary''s Diocesan School for Girls', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('the-glen-high-school', 'The Glen High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('tukssport-high-school', 'TuksSport High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('willowridge-high-school', 'Willowridge High School', 'Gauteng', 'Pretoria', -25.747, 28.229),
  ('ho-rskool-monument', 'Hoërskool Monument', 'Gauteng', 'Krugersdorp', -26.102, 27.775),
  ('ho-rskool-noordheuwel', 'Hoërskool Noordheuwel', 'Gauteng', 'Krugersdorp', -26.102, 27.775),
  ('ferrum-high-school', 'Ferrum High School', 'KwaZulu-Natal', 'Newcastle', -27.746, 29.931),
  ('kearsney-college', 'Kearsney College', 'KwaZulu-Natal', 'Botha''s Hill', -29.745, 30.754),
  ('brettonwood-high-school', 'Brettonwood High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('clifton-school', 'Clifton School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('durban-girls-college', 'Durban Girls'' College', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('durban-girls-high-school', 'Durban Girls'' High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('durban-high-school', 'Durban High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('durban-north-college', 'Durban North College', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('george-campbell-school-of-technology', 'George Campbell School of Technology', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('glenwood-high-school', 'Glenwood High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('maris-stella-school', 'Maris Stella School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('northlands-girls-high-school', 'Northlands Girls'' High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('orient-islamic-school', 'Orient Islamic School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('port-natal-high-school', 'Port Natal High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('st-henry-s-marist-brothers-college', 'St. Henry''s Marist Brothers'' College', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('ohlange-high-school', 'Ohlange High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('folweni-high-school', 'Folweni High School', 'KwaZulu-Natal', 'Folweni', -29.998, 30.894),
  ('ntwenhle-high-school', 'Ntwenhle High School', 'KwaZulu-Natal', 'Folweni', -29.998, 30.894),
  ('siphephele-high-school', 'Siphephele High School', 'KwaZulu-Natal', 'Folweni', -29.998, 30.894),
  ('hillcrest-high-school', 'Hillcrest High School', 'KwaZulu-Natal', 'Hillcrest', -29.783, 30.771),
  ('kloof-high-school', 'Kloof High School', 'KwaZulu-Natal', 'Kloof', -29.789, 30.833),
  ('st-mary-s-diocesan-school-for-girls-2', 'St. Mary''s Diocesan School for Girls', 'KwaZulu-Natal', 'Kloof', -29.789, 30.833),
  ('thomas-more-college', 'Thomas More College', 'KwaZulu-Natal', 'Kloof', -29.789, 30.833),
  ('crawford-international-north-coast', 'Crawford International North Coast', 'KwaZulu-Natal', 'Westbrook', -29.585, 31.159),
  ('pinetown-boys-high-school', 'Pinetown Boys'' High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('pinetown-girls-high-school', 'Pinetown Girls'' High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('savannah-park-secondary-school', 'Savannah Park Secondary School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('st-benedict-school-pinetown', 'St Benedict School Pinetown', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('queensburgh-girls-high-school', 'Queensburgh Girls'' High School', 'KwaZulu-Natal', 'Durban', -29.858, 31.022),
  ('crawford-international-la-lucia', 'Crawford International La Lucia', 'KwaZulu-Natal', 'La Lucia', -29.75, 31.055),
  ('westville-boys-high-school', 'Westville Boys'' High School', 'KwaZulu-Natal', 'Westville', -29.83, 30.924),
  ('westville-girls-high-school', 'Westville Girls'' High School', 'KwaZulu-Natal', 'Westville', -29.83, 30.924),
  ('pholela-high-school', 'Pholela High School', 'KwaZulu-Natal', 'Bulwer', -29.811, 29.763),
  ('st-patrick-s-college', 'St. Patrick''s College', 'KwaZulu-Natal', 'Kokstad', -30.547, 29.425),
  ('ashton-international-college', 'Ashton International College', 'KwaZulu-Natal', 'Ballito', -29.541, 31.211),
  ('stanger-manor-secondary-school', 'Stanger Manor Secondary School', 'KwaZulu-Natal', 'KwaDukuza', -29.333, 31.289),
  ('stanger-secondary-school', 'Stanger Secondary School', 'KwaZulu-Natal', 'KwaDukuza', -29.333, 31.289),
  ('eshowe-high-school', 'Eshowe High School', 'KwaZulu-Natal', 'Eshowe', -28.888, 31.471),
  ('sunnydale-high-school', 'Sunnydale High School', 'KwaZulu-Natal', 'Eshowe', -28.888, 31.471),
  ('port-shepstone-high-school', 'Port Shepstone High School', 'KwaZulu-Natal', 'Port Shepstone', -30.745, 30.451),
  ('phindavele-high-school', 'Phindavele High School', 'KwaZulu-Natal', 'Dududu', -30.203, 30.515),
  ('treverton-college', 'Treverton College', 'KwaZulu-Natal', 'Mooi River', -29.209, 29.993),
  ('alexandra-high-school', 'Alexandra High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('carter-high-school', 'Carter High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('edendale-technical-high-school', 'Edendale Technical High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('epworth-high-school', 'Epworth High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('heritage-academy', 'Heritage Academy', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('linpark-high-school', 'Linpark High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('maritzburg-college', 'Maritzburg College', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('pietermaritzburg-girls-high-school', 'Pietermaritzburg Girls'' High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('russell-high-school', 'Russell High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('st-charles-college', 'St. Charles College', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('st-john-s-diocesan-school-for-girls', 'St. John''s Diocesan School for Girls', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('st-nicholas-diocesan-school', 'St. Nicholas Diocesan School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('the-wykeham-collegiate', 'The Wykeham Collegiate', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('voortrekker-high-school', 'Voortrekker High School', 'KwaZulu-Natal', 'Pietermaritzburg', -29.601, 30.379),
  ('grace-college', 'Grace College', 'KwaZulu-Natal', 'Hilton', -29.551, 30.295),
  ('hilton-college', 'Hilton College', 'KwaZulu-Natal', 'Hilton', -29.551, 30.295),
  ('howick-high-school', 'Howick High School', 'KwaZulu-Natal', 'Howick', -29.481, 30.233),
  ('st-anne-s-diocesan-college', 'St. Anne''s Diocesan College', 'KwaZulu-Natal', 'Hilton', -29.551, 30.295),
  ('michaelhouse', 'Michaelhouse', 'KwaZulu-Natal', 'Balgowan', -29.394, 30.023),
  ('deutsche-schule', 'Deutsche Schule', 'KwaZulu-Natal', 'Hermannsburg', -29.064, 30.641),
  ('estcourt-high-school', 'Estcourt High School', 'KwaZulu-Natal', 'Estcourt', -29.003, 29.87),
  ('drakensberg-boys-choir-school', 'Drakensberg Boys'' Choir School', 'KwaZulu-Natal', 'Winterton', -28.813, 29.537),
  ('inkamana-high-school', 'Inkamana High School', 'KwaZulu-Natal', 'Vryheid', -27.769, 30.791),
  ('mathunjwa-high-school', 'Mathunjwa High School', 'KwaZulu-Natal', 'Vryheid', -27.769, 30.791),
  ('gojela-high-school', 'Gojela High School', 'Limpopo', 'Mahwelereng', -23.811, 29.111),
  ('harry-oppenheimer-agricultural-high-school', 'Harry Oppenheimer Agricultural High School', 'Limpopo', 'Limburg', -23.653, 29.147),
  ('kabelo-high-school', 'Kabelo High School', 'Limpopo', 'Polokwane', -23.896, 29.449),
  ('lebowakgomo-high-school', 'Lebowakgomo High School', 'Limpopo', 'Lebowakgomo', -24.326, 29.608),
  ('leolo-high-school', 'Leolo High School', 'Limpopo', 'Burgersfort', -24.677, 30.327),
  ('phiri-kolobe-high', 'Phiri Kolobe High', 'Limpopo', 'Mankweng', -23.78, 29.681),
  ('st-mark-s-college', 'St Mark''s College', 'Limpopo', 'Jane Furse', -24.757, 29.912),
  ('stanford-lake-college', 'Stanford Lake College', 'Limpopo', 'Haenertsburg', -23.943, 29.947),
  ('vhulaudzi-secondary-school', 'Vhulaudzi Secondary School', 'Limpopo', 'Vhulaudzi', -22.958, 30.617),
  ('segopotje-senior-secondary-school', 'Segopotje Senior Secondary School', 'Limpopo', 'Mashite, Ga Mphalele', -24.398, 29.79),
  ('mokopane-english-combined-school', 'Mokopane English Combined School', 'Limpopo', 'Polokwane', -23.896, 29.449),
  ('barberton-high-school', 'Barberton High School', 'Mpumalanga', 'Barberton', -25.788, 31.044),
  ('penryn-college', 'Penryn College', 'Mpumalanga', 'Mbombela', -25.465, 30.985),
  ('ho-rskool-rob-ferreira-high-school', 'Hoërskool Rob Ferreira High School', 'Mpumalanga', 'Mbombela', -25.465, 30.985),
  ('diamantveld-high-school', 'Diamantveld High School', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('homevale-high-school', 'Homevale High School', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('hts-kimberley', 'HTS Kimberley', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('kimberley-boys-high-school', 'Kimberley Boys'' High School', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('kimberley-girls-high-school', 'Kimberley Girls'' High School', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('st-patrick-s-cbc', 'St. Patrick''s CBC', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('st-boniface-high-school', 'St. Boniface High School', 'Northern Cape', 'Kimberley', -28.728, 24.749),
  ('holy-family-secondary-school', 'Holy Family Secondary School', 'North West', 'Rustenburg', -25.667, 27.242),
  ('j-m-ntsime-high-school', 'J M Ntsime High School', 'North West', 'Rustenburg', -25.667, 27.242),
  ('ntebogang-secondary-school', 'Ntebogang Secondary School', 'North West', 'Dinokana, Zeerust', -25.547, 26.033),
  ('potchefstroom-gimnasium', 'Potchefstroom Gimnasium', 'North West', 'Potchefstroom', -26.716, 27.091),
  ('potchefstroom-high-school-for-boys', 'Potchefstroom High School for Boys', 'North West', 'Potchefstroom', -26.716, 27.091),
  ('tsogo-high-school', 'Tsogo High School', 'North West', 'Mmakau', -25.59, 27.914),
  ('vryburg-high-school', 'Vryburg High School', 'North West', 'Vryburg', -26.957, 24.731),
  ('df-akademie', 'DF Akademie', 'Western Cape', 'Boston', -33.892, 18.626),
  ('stellenberg-high-school', 'Stellenberg High School', 'Western Cape', 'Stellenberg', -33.835, 18.649),
  ('the-settlers-high-school', 'The Settlers High School', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('brackenfell-high-school', 'Brackenfell High School', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('rhodes-high-school', 'Rhodes High School', 'Western Cape', 'Mowbray', -33.947, 18.471),
  ('rondebosch-boys-high-school', 'Rondebosch Boys'' High School', 'Western Cape', 'Rondebosch', -33.963, 18.476),
  ('rustenburg-girls-high-school', 'Rustenburg Girls'' High School', 'Western Cape', 'Rosebank', -33.955, 18.474),
  ('wynberg-boys-high-school', 'Wynberg Boys'' High School', 'Western Cape', 'Wynberg', -34.005, 18.464),
  ('wynberg-girls-high-school', 'Wynberg Girls'' High School', 'Western Cape', 'Wynberg', -34.005, 18.464),
  ('westerford-high-school', 'Westerford High School', 'Western Cape', 'Rondebosch/Newlands', -33.969, 18.466),
  ('fairmont-high-school', 'Fairmont High School', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('ho-rskool-durbanville', 'Hoërskool Durbanville', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('parel-vallei-high-school', 'Parel Vallei High School', 'Western Cape', 'Parel Vallei', -34.079, 18.849),
  ('somerset-college', 'Somerset College', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('false-bay-high-school', 'False Bay High School', 'Western Cape', 'Cape Town', -33.925, 18.424),
  ('makupula-secondary-school', 'Makupula Secondary School', 'Western Cape', 'Stellenbosch', -33.932, 18.863);

UPDATE schools SET city='Johannesburg', lat=-26.198, lng=28.105 WHERE id='sch-jeppe';
UPDATE schools SET city='Pretoria', lat=-25.750, lng=28.229 WHERE id='sch-ptaboys';
UPDATE schools SET city='Pretoria', lat=-25.776, lng=28.232 WHERE id='sch-waterkloof';
UPDATE schools SET city='Rondebosch', lat=-33.963, lng=18.476 WHERE id='sch-rondebosch';
UPDATE schools SET city='Cape Town', lat=-33.962, lng=18.447 WHERE id='sch-bishops';
UPDATE schools SET city='Durban', lat=-29.858, lng=31.022 WHERE id='sch-durbanboys';
UPDATE schools SET city='Bloemfontein', lat=-29.120, lng=26.230 WHERE id='sch-grey';
UPDATE schools SET city='East London', lat=-33.015, lng=27.912 WHERE id='sch-selborne';
